language: python
python:
  - "3.6"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - sudo apt-get update
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda update --yes conda
  - conda info -a
  - conda config --set always_yes yes
  - conda config --add channels conda-forge
  - conda config --add channels mantid/label/nightly
  - conda install python=3.6
  - conda install mantid-framework numpy pandas plotly pylint scipy
  - pip install --upgrade codecov
  - wget http://198.74.56.37/ftp/external-data/MD5/58d6698e1d6bf98e0315687cb980d333 -O REF_M_29160
  - ls -ltr

script:
  - echo 'AR_OUT_DIR_TEMPLATE = "."' >> mr_reduction/settings.py
  - coverage run test/unit_tests.py

after_success:
  - codecov
