language: python
python:
  - "2.7"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - sudo apt-get update
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda update --yes conda
  - conda info -a
  - conda install --yes python=2.7 numpy scipy pylint
  - conda config --add channels conda-forge
  - conda config --add channels mantid
  - conda install --yes -c mantid mantid-framework
  - pip install --upgrade codecov

script:
  - make test
  - cd /tmp/app; coverage run  manage.py test
after_success:
  - codecov
