language: python
python:
  - "3.6"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - sudo apt-get update
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda update --yes conda
  - conda info -a
  - conda install --yes python=3.6 numpy scipy pylint
  - conda config --add channels conda-forge
  - conda config --add channels mantid --add channels mantid/label/nightly
  - conda install --yes -c mantid/label/nightly mantid-framework
  - pip install --upgrade codecov
  - pip install plotly
  - pip install pandas
  - wget http://198.74.56.37/ftp/external-data/MD5/214df921d4fa70ff5a33c4eb6f8284ad -O REF_M_24949
  - wget http://198.74.56.37/ftp/external-data/MD5/58d6698e1d6bf98e0315687cb980d333 -O REF_M_29160
  - ls -ltr
  
script:
  - echo 'AR_OUT_DIR_TEMPLATE = "."' >> mr_reduction/settings.py
  - coverage run test/unit_tests.py

after_success:
  - codecov
