language: python
dist: trusty

python:
  - "3.6"
 
matrix:
  include:
  - os: linux
    env: CONDA=3.6

before_install:
- |
  # Install conda
  "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8 CC=gcc-4.8; fi
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then OS=Linux-x86_64; else OS=MacOSX-x86_64; fi
  wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda${CONDA:0:1}-latest-$OS.sh
  bash miniconda.sh -b -p $HOME/miniconda
  export PATH="$HOME/miniconda/bin:$PATH"
  conda init bash
 
install:
    # Setup conda activate/deactivate commands
  - conda init bash
  - source $(conda info --root)/etc/profile.d/conda.sh
  - conda info --root

    # Conda config - behavior and channel setup
  - conda config --set always_yes yes --set changeps1 no --set anaconda_upload no
  - conda config --add channels conda-forge --add channels mantid --add channels mantid/label/nightly --add channels defaults

    # Install mamba
  - conda install mamba -c conda-forge
  - mamba update mamba -c conda-forge
  - mamba info -a
  
script:
  - mamba create -q -n mr_test python=$CONDA flake8 conda-build anaconda-client pytest pytest-qt pytest-mpl
  - mamba info --envs
  - conda activate mr_test
  
  - conda install --yes numpy scipy pylint
  - conda install -c mantid boost
  - conda install -c mantid poco
  - conda install --yes -c mantid mantid-framework
  
  - pip install --upgrade codecov
  - pip install plotly
  - pip install pandas
  
  - mkdir -p ${CONDA_PREFIX}/conda-bld/linux-64/
  - cp ${PKG_FILE} ${CONDA_PREFIX}/conda-bld/linux-64/
  - ls ${CONDA_PREFIX}/conda-bld
  - ls ${CONDA_PREFIX}/conda-bld/linux-64
  - conda index ${CONDA_PREFIX}/conda-bld
  
  - python --version

  - |
    # Mantid pre-requiste - create a properties file that turns off network access
    mkdir ~/.mantid
    echo "CheckMantidVersion.OnStartup=0" > ~/.mantid/Mantid.user.properties
    echo "UpdateInstrumentDefinitions.OnStartup=0" >> ~/.mantid/Mantid.user.properties
    echo "usagereports.enabled=0" >> ~/.mantid/Mantid.user.properties
    export DISPLAY=:99.0
    sleep 3

  - wget http://198.74.56.37/ftp/external-data/MD5/214df921d4fa70ff5a33c4eb6f8284ad -O REF_M_24949
  - wget http://198.74.56.37/ftp/external-data/MD5/58d6698e1d6bf98e0315687cb980d333 -O REF_M_29160
  - ls -ltr
  
script:
  - echo 'AR_OUT_DIR_TEMPLATE = "."' >> mr_reduction/settings.py
  - coverage run test/unit_tests.py

after_success:
  - codecov
